In [1]:
import pandas as pd
import numpy as np

In [2]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer

In [3]:
boW = CountVectorizer(ngram_range=(1, 1))
tfidf = TfidfVectorizer(ngram_range=(1, 1))

In [4]:
df_train = pd.read_csv("cleaned_data.csv")
df_train.head()

Unnamed: 0  Final_Summary_Reg_Lower_Lem_StopWords_NullRemoval  Score
0      395199  ['gluten', 'wish', 'chip', 'lish', 'love', 'fr...      5
1      567152  ['food', 'given', 'yumm', 'great', 'get', 'sid...      4
2      335690  ['come', 'east', 'middle', 'parent', 'produced...      5
3      335587  ['listed', 'coloring', 'dog', 'sifting', 'prot...      4
4      148871  ['used', 'great', 'also', 'making', 'one', 'st...      5

In [5]:
df_train.drop('Unnamed: 0', axis=1, inplace=True)

In [6]:
df_train.head()

Final_Summary_Reg_Lower_Lem_StopWords_NullRemoval  Score
0  ['gluten', 'wish', 'chip', 'lish', 'love', 'fr...      5
1  ['food', 'given', 'yumm', 'great', 'get', 'sid...      4
2  ['come', 'east', 'middle', 'parent', 'produced...      5
3  ['listed', 'coloring', 'dog', 'sifting', 'prot...      4
4  ['used', 'great', 'also', 'making', 'one', 'st...      5

In [7]:
X_train = tfidf.fit_transform(df_train["Final_Summary_Reg_Lower_Lem_StopWords_NullRemoval"])
X_train

<397624x83400 sparse matrix of type '<class 'numpy.float64'>'
	with 12444975 stored elements in Compressed Sparse Row format>

In [8]:
y_train = df_train.Score
y_train.head()

0    5
1    4
2    5
3    4
4    5
Name: Score, dtype: int64

In [9]:
len(tfidf.get_feature_names_out())

83400

In [10]:
tfidf.vocabulary_

{'gluten': 30889,
 'wish': 81364,
 'chip': 12773,
 'lish': 42296,
 'love': 42957,
 'free': 28712,
 'wheat': 80688,
 'taste': 72717,
 'dee': 18642,
 'bag': 5279,
 'per': 54054,
 'world': 81797,
 'food': 28102,
 'given': 30619,
 'yumm': 82854,
 'great': 31826,
 'get': 30269,
 'side': 66243,
 'protein': 57684,
 'feeling': 26656,
 'portable': 56152,
 'enjoy': 24017,
 'high': 34254,
 'full': 29318,
 'desk': 19659,
 'golean': 31140,
 'meal': 45083,
 'chocolate': 12983,
 'bar': 5574,
 'satisfied': 63760,
 'nice': 49200,
 'usually': 78170,
 'keep': 39595,
 'take': 72359,
 'cannot': 10594,
 'kashi': 39445,
 'different': 20238,
 'work': 81764,
 'better': 6820,
 'prepackaged': 56806,
 'sweet': 71864,
 'way': 80209,
 'type': 76341,
 'little': 42367,
 'cal': 10196,
 'overall': 52102,
 'replacement': 61086,
 'concern': 15111,
 'fiber': 26912,
 'wanted': 79949,
 'day': 18252,
 'security': 64777,
 'lunch': 43214,
 'tasty': 72787,
 'something': 68002,
 'low': 43017,
 'change': 12001,
 'come': 14599,
 '

In [11]:
# df_boW = pd.DataFrame(X_train.toarray(), columns=boW.get_feature_names_out())
# df_boW.head()

In [11]:
df_test = pd.read_csv("cleaned_data_test.csv")
df_test.head()

Unnamed: 0  Final_Summary_Reg_Lower_Lem_StopWords_NullRemoval  Score
0       26249  ['pack', 'never', 'lover', 'purchasing', 'tast...      1
1      293673  ['seems', 'probably', 'replaced', 'like', 'wor...      3
2       48841  ['butter', 'prefer', 'others', 'chocolate', 'o...      1
3      270004  ['amazon', 'price', 'save', 'always', 'disappo...      3
4       46028  ['loose', 'price', 'smooth', 'cup', 'leaf', 'l...      5

In [12]:
df_test.drop('Unnamed: 0', axis=1, inplace=True)
df_test.head()

Final_Summary_Reg_Lower_Lem_StopWords_NullRemoval  Score
0  ['pack', 'never', 'lover', 'purchasing', 'tast...      1
1  ['seems', 'probably', 'replaced', 'like', 'wor...      3
2  ['butter', 'prefer', 'others', 'chocolate', 'o...      1
3  ['amazon', 'price', 'save', 'always', 'disappo...      3
4  ['loose', 'price', 'smooth', 'cup', 'leaf', 'l...      5

In [13]:
X_test = tfidf.transform(df_test["Final_Summary_Reg_Lower_Lem_StopWords_NullRemoval"])
X_test

<170411x83400 sparse matrix of type '<class 'numpy.float64'>'
	with 5320186 stored elements in Compressed Sparse Row format>

In [14]:
y_test = df_test.Score

In [15]:
from sklearn.tree import DecisionTreeClassifier
dt_classifier = DecisionTreeClassifier()

In [16]:
%%time
# Decision Tree Classifier
dt_classifier.fit(X_train, y_train)

y_pred = dt_classifier.predict(X_test)
y_pred

CPU times: user 1h 6min 19s, sys: 48 s, total: 1h 7min 7s
Wall time: 1h 44min 23s


array([5, 3, 5, ..., 1, 5, 5])

In [64]:
%%time
# RandomForest Classifier
from sklearn.ensemble import RandomForestClassifier
rf_classifier = RandomForestClassifier()

rf_classifier.fit(X_train, y_train)

y_pred_rf = rf_classifier.predict(X_test)
y_pred_rf

CPU times: user 1h 57min 51s, sys: 1min 29s, total: 1h 59min 21s
Wall time: 2h 33min 2s


array([5, 3, 5, ..., 5, 5, 5])

In [21]:
y_pred_rf = rf_classifier.predict(X_test)
y_pred_rf

NameError: name 'rf_classifier' is not defined

In [22]:
%%time
# XGBoost Classifier
from sklearn.ensemble import GradientBoostingClassifier
xgb_classifier = GradientBoostingClassifier()

xgb_classifier.fit(X_train, y_train)

y_pred_xg = xgb_classifier.predict(X_test)
y_pred_xg

CPU times: user 1h 24min 27s, sys: 1min 49s, total: 1h 26min 17s
Wall time: 1h 33min 50s


array([5, 3, 5, ..., 5, 5, 5])

In [18]:
def metric_class(classifier, y_pred, y_test):
    from sklearn.metrics import accuracy_score, classification_report, precision_score, confusion_matrix
    print("*"*116)
    print("Classifier: ", classifier)
    print("*"*40)
    accuracy_score_ = accuracy_score(y_pred, y_test)
    print("accuracy_score:", accuracy_score_)
    print("*"*40)
#     conf_matrix = confusion_matrix(y_pred, y_test)
#     print("Confusion Matrix:", conf_matrix)
#     print("*"*40)  
    class_report = classification_report(y_pred, y_test)
    print("Classification Report: \n")
    print(class_report)


In [19]:
metric_class("Decision Tree classifier", y_pred, y_test)
metric_class("Random Forest classifier", y_pred_rf, y_test)
# metric_class("Decision Tree", y_pred, y_test)

********************************************************************************************************************
Classifier:  Decision Tree classifier
****************************************
accuracy_score: 0.7512425841054862
****************************************
Classification Report: 

              precision    recall  f1-score   support

           1       0.64      0.65      0.64     15475
           2       0.46      0.51      0.48      7966
           3       0.49      0.54      0.51     11617
           4       0.52      0.54      0.53     23374
           5       0.87      0.85      0.86    111979

    accuracy                           0.75    170411
   macro avg       0.59      0.62      0.60    170411
weighted avg       0.76      0.75      0.75    170411



NameError: name 'y_pred_rf' is not defined

In [ ]:
from wordcloud import WordCloud

In [ ]:
df = pd.read_csv("cleaned_data.csv")
df.head()
df_review1 = df.loc[df["Score"]==1,:] 
df_review1


In [ ]:
len(words)

In [ ]:
wordCloud_ = WordCloud(
    max_words=2500,
    width=800,
    height=1500,
    ).generate()